[tools]
java = "17"
node = "24"
terraform = "1.14"
python = "3.13"
rust = "1.91"
ruby = "3.3.10"
flutter = "3.38"
go = "1.25"
shellcheck = "0.11"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python", "go", "node"]
